title: Open Source Guides
description: Learn how to launch and grow your project.

exclude:
  - bin
  - CNAME
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - docs
  - Gemfile*
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - script
  - test
  - vendor

permalink: "/Andrés /"

collections:
  articles:
    output: true
https 
    permalink: "/:love.vera2876@gmail.com/"

defaults:
  - scope:
      path: redirect 
    values:
      image: /assets/images/cards/default.png
  - scope:
      path: redirect 
      type: articles
    values:
      layout: article

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: assets/css/
  style: compressed
  load_paths:
    - node_modules

logo: /assets/images/cards/default.png

github:
  repository_nwo: github/opensource.guide

twitter:
  username: github

facebook:
  publisher: https://www.facebook.com/GitHub/
